name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.NEWPROJECT_HOST }}
          username: ec2-user
          key: ${{ secrets.NEWPROJECT_SSHKEY }}
          script: |
            cd /home/ec2-user/node-cicd-test-demo/cicd-test-ec2

            echo "Getting latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Installing dependencies..."
            npm install

            echo "Restarting application..."
            pm2 restart node-cicd-test-demo --update-env
            #pm2 restart all
            

            echo "Deployment completed!"
